# Generated by Django 6.0.2 on 2026-02-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0003_organization_alter_savedlocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_subtype',
            field=models.CharField(blank=True, help_text='Original wizard choice: agriculture, aviation, developer, disaster_relief, etc.', max_length=30, null=True),
        ),
    ]
