# Generated by Django 6.0.2 on 2026-03-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0004_organization_org_subtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='global_default', max_length=100)),
                ('version', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('resumed', 'Resumed'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('required_role', models.CharField(default='admin', max_length=20)),
                ('paused_at_step', models.CharField(blank=True, max_length=40, null=True)),
                ('resume_from_step', models.CharField(blank=True, max_length=40, null=True)),
                ('pending_action', models.CharField(blank=True, max_length=120, null=True)),
                ('user_query', models.TextField(blank=True, default='')),
                ('location_name', models.CharField(blank=True, default='Location', max_length=255)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('selected_graph', models.CharField(default='standard_forecast_graph', max_length=80)),
                ('pipeline', models.JSONField(blank=True, default=list)),
                ('task_ledger', models.JSONField(blank=True, default=list)),
                ('partial_results', models.JSONField(blank=True, default=dict)),
                ('message_state', models.JSONField(blank=True, default=dict)),
                ('checkpoint_payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workflow_checkpoints', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_checkpoints', to=settings.AUTH_USER_MODEL)),
                ('execution_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_checkpoints', to='guardian.agentexecutionlog')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_checkpoints', to='guardian.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
